name: jcefsampleapp-release

on:
  workflow_dispatch:
    inputs:
      build_meta:
        description: 'Build meta to use as source'
        required: true
      mvn_version:
        description: 'jcefmaven version to use as source'
        required: true

jobs:
  jcefsampleapp-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate release info
        run: |
          cd scripts
          chmod +x create_release_info.sh
          ./create_release_info.sh ${{ github.event.inputs.build_meta }} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}} ${{github.run_number}} ${{ github.event.inputs.mvn_version }}
      - name: Create Release
        run: |
          gh release create ${{env.release_tag_name}} --title "${{env.release_name}}" --notes-file release_info/release_message.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get release info
        run: |
          echo "upload_url=$(gh release view ${{env.release_tag_name}} --json upload_url --jq '.upload_url')" >> $GITHUB_ENV
      - name: Print release info
        run: |
          echo "Using upload url ${{ env.upload_url }}"
      - name: Add build_meta.json       
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: release_info/build_meta.json                                                           
          asset_name: build_meta.json                                     
          asset_content_type: application/json
      - name: Build jcefsampleapp
        run: chmod +x generate_artifacts.sh && ./generate_artifacts.sh ${{ github.event.inputs.mvn_version }}
      - name: Add jcefsampleapp artifact       
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: out/jcefsampleapp-${{ github.event.inputs.mvn_version }}-jar-with-dependencies.jar                                                           
          asset_name: jcefsampleapp-${{ github.event.inputs.mvn_version }}-jar-with-dependencies.jar                                     
          asset_content_type: application/json
